### ISSUE TITLE
[PLEASE] Force update for testing (at least on a different page or idk)

### ISSUE THREAD

**Issue by iGabyTM** [Bastian/bStats#100]
Add a way to either force an update for the data or smth in-game. It's so frustrating that you have to wait 30 minutes to see if your code worked or nah.

**Comment by OskarZyg** [comment]
With some hackery, you can start a local instance of bstats and work with that.

**Comment by MiniDigger** [comment]
there is a cool thing called unit test. if allows you to test your code without testing 3rd party stuff. you should check that out!

**Comment by iGabyTM** [comment]
I'm talking about bstats stuff but ok, maybe I overthink this.
