### ISSUE TITLE
Cannot compile plugins with bStats integration (maven repo down?)

### ISSUE THREAD

**Issue by TheSteveRizzo** [Bastian/bStats#104]
Hi, I have reason to believe the Maven repository may be down regarding the bStats plugin. After trying to compile plugins using Maven that have a dependency of this plugin, the repository URL fails to download. 

Please advise.

**Comment by MiniDigger** [comment]
Which repo do you use? Check the bstats site on the updated way to integrate bstats (uses the codemc repo)
https://bstats.org/getting-started/include-metrics

**Comment by TheSteveRizzo** [comment]
Upon further investigation, I am lead to believe that the error Maven is throwing is due to a separate project's dependencies still listing the old bStats repository and is not an issue with bStats. More specifically, when using the MobArena project as a dependency in my project, the error occurs (probably using the old repo). I've since contacted the author and will update this report after finding out more information.

**Comment by TheSteveRizzo** [comment]
This is confirmed to be an issue related to MobArena's pom.xml (updating repository/dependency links). I'll go ahead and close this issue.

Thanks for the support! :)
