### ISSUE TITLE
I am getting 522:Connection timed out at repo.bstats.org

### ISSUE THREAD

**Issue by unwillexist** [Bastian/bStats#106]
And cannot build 

         > Could not get resource 'http://repo.bstats.org/content/repositories/releases/cpw/mods/modlauncher/2.1.1/modlauncher-2.1.1.pom'.
            > Could not GET 'http://repo.bstats.org/content/repositories/releases/cpw/mods/modlauncher/2.1.1/modlauncher-2.1.1.pom'.
Received status code 522 from server: Origin Connection Time-out

I am living in Turkey, is there any chance that are you guys blocked Turkey ? 

https://ibb.co/wBjP4HF

And sorry, this is not look like a proper place to submit this issue but I didn't saw any information of contact at your site.

**Comment by MiniDigger** [comment]
that repo was retired long time ago. remove it from your project.

see this page for how to include bstats in your projects https://bstats.org/getting-started/include-metrics

**Comment by unwillexist** [comment]
Thank you.
