### ISSUE TITLE
Somebody posted my plugin and they are not the owner

### ISSUE THREAD

**Issue by SunnyYT** [Bastian/bStats#107]
I need access of my plugin on bStats.org since I need to add some new charts but someone added the plugin without my permission since I forgot to add it myself after I added metrics. I need access back and I can prove ownership and everything. My bstats account is neoSunny.

**Comment by MiniDigger** [comment]
Are you sure that it's not just somebody else's plugin with the same name?

**Comment by SunnyYT** [comment]
I am not really sure about that but the page was inactive before I added metrics to my plugin so is it possible to remove the plugin so I can re-add mine?

**Comment by Bastian** [comment]
Hi,
please send me
- The name of the plugin
- Some proof that it is your plugin.

If it is a plugin on Spigot, sending me a message on spigotmc.org is enough proof :)
(https://www.spigotmc.org/members/btobastian.87698/)

I can delete the old plugin or just transfer it your account.

**Comment by SunnyYT** [comment]
I replied on your public profile with resource name on spiogot

**Comment by Bastian** [comment]
Done :)
