### ISSUE TITLE
Request to shift owner on dynmap plugin

### ISSUE THREAD

**Issue by mikeprimm** [Bastian/bStats#108]
Greetings - and my complements on your service!
I wanted to request that the owner associated with my plugin, dynmap, be shifted from @KovuTheHusky to my account (also mikeprimm on the bstats site).  KovuTheHusky had contributed some PRs to dynmap over the years, and I appreciate him registering the plugin with your service, but I am, in fact, the owner of the plugin and would appreciate the appropriate ownership of the registration.  Please let me know if there is any other proof required - I figues my tie to the source code here - https://github.com/webbukkit/dynmap - should be adequate.

**Comment by KovuTheHusky** [comment]
@mikeprimm is indeed the owner and I meant to ask about transferring ownership back when I switched dynmap over to bstats from mcstats. I believe I wasn't sure how to get in touch at the time.

If there's anything I can do to help please let me know!

**Comment by mikeprimm** [comment]
@KovuTheHusky thanks!!

**Comment by Bastian** [comment]
I've transfered the plugin to your account :)
