### ISSUE TITLE
Feature request: Add Java 11 and 12 to Java version detection

### ISSUE THREAD

**Issue by SlimeDog** [Bastian/bStats#111]
The "Other" in this case is
```
$ java -version
java version "11.0.6" 2020-01-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.6+8-LTS, mixed mode)
```
which is displayed only if I click on it.

![Screen Shot 2020-01-18 at 9 13 18 AM](https://user-images.githubusercontent.com/17748923/72667640-e0768300-39d2-11ea-96c9-8ed9df89653a.png)

![Screen Shot 2020-01-18 at 9 13 33 AM](https://user-images.githubusercontent.com/17748923/72667641-e53b3700-39d2-11ea-9f21-4a658bbcdbc8.png)

**Comment by MiniDigger** [comment]
might help to provide the link as an example

**Comment by SlimeDog** [comment]
Any plugin, or just [https://bstats.org/global/bukkit](https://bstats.org/global/bukkit). Java 11 and 12 are reported in "Other", even if they are a large percentage.

**Comment by DoNotSpamPls** [comment]
https://github.com/Bastian/bStats/blob/89a0fc6913993759e248d54b0e2ee6e25c14aa7b/routes/submitData.js#L169

**Comment by SlimeDog** [comment]
Thanks. Changed to feature request.

**Comment by MiniDigger** [comment]
might as well add the next like 10 versions. java 13 is already release, java 14 will come in march and java 15 in September.

**Comment by Bastian** [comment]
"Fixed" in https://github.com/Bastian/bStats/commit/d0d3a36592618f6fe536873c02297d0b796f84bb
The change will be visible in 30 minutes.

**Comment by SlimeDog** [comment]
And there it is. Thank you.
