### ISSUE TITLE
[Question] - How change my username?

### ISSUE THREAD

**Issue by Olyno** [Bastian/bStats#114]
Hi,
I changed a moment ago my username, and my bstats account still have my old username. There are any way to change it?

**Old name:** AlexLew
**New name:** Olyno

Thanks, Olyno.

**Comment by MiniDigger** [comment]
there is no proper process, I think the easiest way to to PM btobastian on spigot with your request, so he can verify that you are you

**Comment by Bastian** [comment]
I've answered your message on Spigot. :)
