### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by PikaMug** [Bastian/bStats#116]
I'm trying to get better acquainted with this project (and JavaScript runtimes in general), but am having trouble setting up.

Running NodeJS on a Win7 machine with https://github.com/microsoftarchive/redis

I've got Redis up on port 6379 and have modified bStats' config.yml accordingly. When I run `node app.js`, there's nothing at localhost:3000. I've added a console.log to the end of the file, so I know it completes. What am I overlooking?

**Comment by Bastian** [comment]
You have to run one of the two files in the `/bin` folder.
`start.js` spawns multiple instances, `www.js` only one.
You might also need to adjust the Redis config a little bit if you are not using a Redis cluster.

**Comment by PikaMug** [comment]
Thanks! I've got an active connection, but nothing loads. I'll take your advice and look into setting up a cluster.

**Comment by Bastian** [comment]
You also have to run the `redisPopulator.js` file once.

**Comment by PikaMug** [comment]
@Bastian I figured that might be the case. Gave me an error in standalone, but it runs fine in cluster mode. Unfortunately, `node www.js` still gives me perpetual "Waiting for Localhost..." in Chrome.

**Comment by MiniDigger** [comment]
It might me way easier to debug this if you join discord: https://discord.gg/qTXtXuf
