### ISSUE TITLE
My plugins show no data on bstats website.

### ISSUE THREAD

**Issue by teozfrank** [Bastian/bStats#117]
Hi I have added my plugins:

https://bstats.org/plugin/bukkit/UltimateVotes/

https://bstats.org/plugin/bungeecord/UltimateVotesBungee/

Both are showing no stats even though it seems to be sending the data to the server:

![image](https://user-images.githubusercontent.com/3265598/83064208-5bbf0400-a059-11ea-875a-8b1542228957.png)

I dont see any message for my spigot plugin sending data but it does show worldedit sending data, if there is worldedit and my plugin on spigot server should it send its data as well? I dont seem to see it in the logs.

**Comment by Bastian** [comment]
The `plugins` Array is empty. That's weird.

Did you modify the bStats Metrics class? E.g. obfuscated it?

**Comment by teozfrank** [comment]
> 
> 
> The `plugins` Array is empty. That's weird.
> 
> Did you modify the bStats Metrics class? E.g. obfuscated it?

Actually, yes I obfucate it, that makes sense! Should I exclude the metrics class from obfuscation?

**Comment by Bastian** [comment]
Yes. Exclude it and everything should work fine :)

**Comment by teozfrank** [comment]
Still the same problem after exclusion, is there something I am missing? I am using proguard and excluding the class with: ->-keep class path.to.metrics.class.Metrics

**Comment by DoNotSpamPls** [comment]
Are you obfuscating the main class?

**Comment by teozfrank** [comment]
Yes, that wasn't the problem. I had it obfuscating the methods in the Metrics class too, I removed this and it seems to be submitting correct data now :)

![image](https://user-images.githubusercontent.com/3265598/83357145-83b4ad00-a362-11ea-8718-a49a4d819851.png)

Took a little bit of debugging on the spigot side, turns out I had to tell proguard to not modify the B_STATS_VERSION field, seems to work now !! :)

![image](https://user-images.githubusercontent.com/3265598/83361163-8de4a480-a37e-11ea-9a67-d439165f36b3.png)
