### ISSUE TITLE
Doubble Count in bStats

### ISSUE THREAD

**Issue by Wolf2323** [Bastian/bStats#133]
This is my bStats page: https://bstats.org/plugin/bukkit/BetonQuest/551
Some time ago, i added a drilldown chart with the Plugin Version and if you click on them you can also see the Minecraft version.

Now if i look ok that chart https://bstats.org/api/v1/plugins/551/charts/versionBqMc/data i see, that there are `11` `1.12.0` Servers.
But if i look ath the pluginVersion chat that exist by default https://bstats.org/api/v1/plugins/551/charts/pluginVersion/data i see `22` `1.12.0` Servers.

Also the absolut amount of the pluginVersion's looks like it the the double of the server count.

Also if you look at the data there are no odd numbers.

**Comment by Bastian** [comment]
Thanks for reporting!

I've just deployed a bugfix and the correct data should be visible in 30 minutes.
