### ISSUE TITLE
Request to transfer ownership

### ISSUE THREAD

**Issue by martinambrus** [Bastian/bStats#139]
Hi, I would like to ask transfer of ownership of the plugin AdminAnything (https://bstats.org/plugin/bukkit/AdminAnything/1435) to MrMicky (https://bstats.org/author/MrMicky), as he is now the one maintaining my plugin (https://www.spigotmc.org/threads/adminanything-take-back-control-of-your-server-paid.129168/page-17#post-4159687)

Thank you :)

**Comment by Bastian** [comment]
Done :)
