### ISSUE TITLE
Question: Chart order

### ISSUE THREAD

**Issue by SlimeDog** [Bastian/bStats#143]
It looks like some authors have discovered how to modify the page layout, both by moving custom charts into the standard area (above the map) and by moving standard charts into the custom area (below the map). [ItemJoin](https://bstats.org/plugin/bukkit/ItemJoin/4115) is an example.

I have not found the secret to modify the page layout. Please advise.

**Comment by mdcfe** [comment]
You can click and drag the bars to the left of the charts:

![2021-09-06_16-34-20](https://user-images.githubusercontent.com/1917406/132239856-5b743d92-ca2b-4f80-b87f-115bdfa68677.gif)

**Comment by SlimeDog** [comment]
Cool. Thanks.
