### ISSUE TITLE
How add my minecraft server core to bstats?

### ISSUE THREAD

**Issue by NONPLAYT** [Bastian/bStats#158]
Paper have "Server implementation" and I have a question: How add my own server core to bstats?

**Comment by ColdeZhang** [comment]
Hey @NONPLAYT , have you figured out how to add a "Server implementation" type? I have the same question.

**Comment by NONPLAYT** [comment]
> Hey @NONPLAYT , have you figured out how to add a "Server implementation" type? I have the same question.

join bstats discord server and ask to add your Server implementation in #suggestions channel

**Comment by ColdeZhang** [comment]
> > Hey @NONPLAYT , have you figured out how to add a "Server implementation" type? I have the same question.
> 
> 
> 
> join bstats discord server and ask to add your Server implementation in #suggestions channel

Alright, thanks for replying :). That's a little bit complicated.
