### ISSUE TITLE
Adding a plugin shows 'Please solve the captcha!' but I don't see anything related to captcha.

### ISSUE THREAD

**Issue by plaidmrdeer** [Bastian/bStats#160]
Adding a plugin shows 'Please solve the captcha!' but I don't see anything related to captcha.

![QQ图片20230424124138](https://user-images.githubusercontent.com/98594477/233901625-8fe94c13-94c2-453d-bf55-aa6ee8553b21.png)

**Comment by plaidmrdeer** [comment]
> 尝试使用其他浏览器，没有任何浏览器扩展，还可以查看浏览器控制台以查看任何错误

When adding a plugin to bstats, the console displays 'Failed to load resource: net::ERR_CONNECTION_TIMED_OUT', but there are no issues with my network connection.

**Comment by plaidmrdeer** [comment]
> try in a different browser and without any browser extensions, also take a look at the browser console to see any errors

When adding a plugin to bstats, the console displays 'Failed to load resource: net::ERR_CONNECTION_TIMED_OUT', but there are no issues with my network connection.

**Comment by Bastian** [comment]
Are you located in China? I'm afraid that their great firewall block the captcha as it is from Google.

Do you have similar problems on other sites that use Google's Recaptcha?

**Comment by plaidmrdeer** [comment]
> Are you located in China? I'm afraid that their great firewall might block the captcha as it is from Google.
> 
> Do you have similar problems on other sites that use Google's Recaptcha?

Thank you for your answer, I have resolved the issue. However, I don't understand why I didn't need to use a VPN when adding the plugin last time, but I needed to use it this time.
