### ISSUE TITLE
Forgot Password

### ISSUE THREAD

**Issue by ToxicStoxm** [Bastian/bStats#163]
Username: x_Tornado10
I use NordPASS but i forgot to unlock it, so it did not save my password i set when creating my account. What can I do?

**Comment by Bastian** [comment]
Hello,

Unfortunately there's no automatic way to change your password at the moment. However, I can update it manually. For this I need
• A proof of account ownership (usually a message on SpigotMC: <https://www.spigotmc.org/members/btobastian.87698/>)
• A bcrypt hash of your new password (you can generate one here: <https://www.browserling.com/tools/bcrypt>)
• The name of your account

**Comment by ToxicStoxm** [comment]
I send you a message saying "Proof this is my account",
Password hash: $2a$10$g5UOtd4uvrPEasayocTv3.xhGfLjosxm94sWlROghHDLGdhKJb2Y2
Account name: x_Tornado10

Am Sa., 22. Juli 2023 um 10:55 Uhr schrieb Bastian Oppermann <
***@***.***>:

**Comment by Bastian** [comment]
Please send me a new bcrypt hash as a Spigot direct message. Although sharing the hash publicly is theoretically safe, assuming a secure password, it is still not recommended due to potential security risks associated with exposing any sensitive information unnecessarily.
