### ISSUE TITLE
Add shields like GitHub

### ISSUE THREAD

**Issue by darbyjack** [Bastian/bStats#28]
I think it'd be really cool to portray on your plugin website / on spigot a "Shield" like GitHub has, where it would say "Server #/#" and "Players #/#" to show people interested in your plugin that this many servers are using it currently.

**Comment by sgdc3** [comment]
Nice idea!

**Comment by MiniDigger** [comment]
not sure how hard it is to generate such shields (they are svg's), but someone could easily fork shield.io and add new shields, assuming that bstats has a api which provides the necessary data.

**Comment by BtoBastian** [comment]
Hey,
it's pretty easy to do this yourself using the REST api and a little bit of php.

The example below uses Unirest (http://unirest.io/php.html):
```php
<?php
require_once 'Unirest.php';

function getServers ()
{
  Unirest\Request::verifyPeer(false);
  $headers = array('Accept' => 'application/json');
  $url = "https://www.bstats.org/api/v1/plugins/4/charts/servers/data";
  
  $response = Unirest\Request::get($url, $headers);
  $array = array_reverse($response->body);
  return $array[0][1];
}

header('Content-Type: image/svg+xml');
readfile('https://img.shields.io/badge/servers-'.getServers().'-brightgreen.svg');
exit;
?>
```
and creates the following output:
http://bastian-oppermann.de/SafeTrade/ExampleServersShield.php + using the following RewriteRule in the .htaccess
```
RewriteRule ^ExampleServersShield.svg$ ExampleServersShield.php
```
you can embed it very easily like normal shields.io: ![](http://bastian-oppermann.de/SafeTrade/ExampleServersShield.svg)

**Comment by Bastian** [comment]
Cool, thanks for adding this to shield.io. 👍 
Taking a quick look at your PR, I guess this was the reason for https://github.com/Bastian/bStats/issues/85?
