### ISSUE TITLE
Change plugins to be identified by UUID rather than name

### ISSUE THREAD

**Issue by Narimm** [Bastian/bStats#40]
For example I am adding a new Plugin - thats has existed for over 10 years - up until now it use the old Metrics so I am switching it to bstats - but when I add the plugin it says it already exists despite the fact there is no plugin by that name listed.. This presents a problem from the point of view its highly likely there will be 2 plugins with the same name that are completely different - I think it would be smarter to assign a Plugin a UUID on the website and initialize it
Metrics metrics = new Metrics(plugin);
metrics.setPluginID(<uuid>);
metrics.addCustomChart(charts);

**Comment by Narimm** [comment]
Also you should provide a mechanism for that ensure people have to prove plugin ownership to stop random registrations that block real plugin developers  Although seperating the name from rego will go a long way to rectifying this

**Comment by randombyte-developer** [comment]
Instead of an UUID I would suggest using the real plugin ID/qualified package name.

**Comment by Derkades** [comment]
"the real plugin ID"

What would this be?

**Comment by Narimm** [comment]
Real plugin ID? is arbitrary anyway, and as for the qualified name package - arguably if a plugin gets forked 400 times how do you know who is using your fork?

**Comment by Narimm** [comment]
Look even UUID isnt going to stop someone polluting stats if they really want to.. I would tend to build the UUID declaration into the build cycle rather than hardcode it...

**Comment by DoNotSpamPls** [comment]
I feel that would be kind of useless, since what would it help with? A URL like /plugin/bukkit/cde6a27a-e24c-4281-9b49-1e8684331074 wouldn't be very user friendly. Also, if there are two plugins with the same name, the developer of the newer plugin is doing it wrong - a plugin name should **never** be ambiguous.

**Comment by Bastian** [comment]
My ideas was the following:
- A new version of the Metrics class which takes the plugin-id as a parameter for the constructor
- Have an url like most forums: https://bStats.org/plugins/software/pluginname-id/ e.g. https://bStats.org/plugins/software/MyAwesomePlugin-1234/

**Comment by mrgeneralq** [comment]
I have to agree here. I love bStats! But the fact that people stole my plugin name is frustrating.

**Comment by PikaMug** [comment]
This should probably be closed as the current discussion on this is at #70

**Comment by Bastian** [comment]
Agreed
