### ISSUE TITLE
Drilldown Pie - not working as expected

### ISSUE THREAD

**Issue by NiklasEi** [Bastian/bStats#55]
Following scenario:
I have a plugin that has some number of inventory games. Every server can have different games and a different amount of games. Now I'd like to have a drilldown pie with the number of games on the first stage and the games distribution of all servers with the same number of games on the second stage.
```java
        metrics.addCustomChart(new Metrics.DrilldownPie("games_drill_down", () -> {
            Map<String, Map<String, Integer>> map = new HashMap<>();
            Map<String, Integer> entry = new HashMap<>();
            for (String gameID : getPluginManager().getGames().keySet()) {
                entry.put(getOriginalGameName(gameID), 1);
            }
            map.put(String.valueOf(getPluginManager().getGames().size()), entry);
            return map;
        }));
```
I would expect that every plugin instance gets a weight of 1 for the first stage (it's 1 time n games). So if I have 4 servers with different numbers of plugins every server gets 25% of the cake. But instead, with the code above, the value on the first stage is given by the number of games ([screenshots](https://imgur.com/a/K8R7n)).

I am not 100% sure that this is an issue. Maybe you want the drilldown pie to act like this, but I was ecpecting a different behaviour.

**Comment by BtoBastian** [comment]
Hey, thank you for the report.

> Maybe you want the drilldown pie to act like this, but I was ecpecting a different behaviour.

The current behavior is exactly how it is supposed to work: The first stage just shows the amount of elements in the second stage. There are probably use-cases for both behaviors.
I don't know your plugin, so maybe I'm wrong, but wouldn't it make more sense to have the game type in the first stage and the number of games in the second stage?

**Comment by NiklasEi** [comment]
I would mostly be interested in what games servers are running, if they only have a small amount of games installed. That would be a use-case for the behavior I was expecting. If I use the game names on the first stage I would have to click through all games and look at the second stages to get that kind of information.

I tried finding other usages for the implemented behavior and looked through the top 20 plugins, but was unable to find a custom Drilldown Pie. Do you have an example?

The two default Drilldown Pies (java version and operating system) are identical in both behaviors, since they always have only one entry per server.

**Comment by BtoBastian** [comment]
I'm not sure if there's any plugin which depends on the current behavior. I'll take a look, if I maybe can implement some kind of flag, which allows you to decide which behavior you want.

**Comment by NiklasEi** [comment]
I'll close this since I no longer need it.
