### ISSUE TITLE
[github] Add a CI and depedency management bot

### ISSUE THREAD

**Issue by DoNotSpamPls** [Bastian/bStats#68]
Travis-CI and Greenkeeper come to mind - they take no more than 10 minutes to setup and will (hopefully) make the software a bit more easier to maintain 😃

**Comment by MiniDigger** [comment]
greepkeeper is meh, it misses updates and sometimes doesn't rebase prs.
I would suggest renevate as an alternative https://renovatebot.com/

**Comment by sgdc3** [comment]
We can also use our jenkins at codemc.io :) For dependencies, what about dependabot?
