### ISSUE TITLE
Provide a png thumbnail for easy embedding of graphs elsewhere

### ISSUE THREAD

**Issue by rlf** [Bastian/bStats#73]
One of the nice features of mcstats was, that you could link to a .png version of the graph, and thus embed graphs in various places (I.e. Spigot and Bukkit.org).

I really miss that feature.

**Comment by Plajer** [comment]
Do you mean signatures? https://bstats.org/signatures/bukkit/VillageDefense.svg

**Comment by Bastian** [comment]
bStats has signatures images as a beta-feature available.
The links has the following format:
```
https://bstats.org/signatures/<software>/<plugin>.svg
```
e.g.
```
https://bstats.org/signatures/bukkit/SafeTrade.svg
```
which look like this:
![](https://bstats.org/signatures/bukkit/SafeTrade.svg)

Be aware, that this is a beta feature tho!
It's very likely that the URL will change one day and your embed images will no longer be displayed correctly. I don't think that's a huge problem as you can just swap out the links then.

**Comment by rlf** [comment]
Thanks man!
