### ISSUE TITLE
Will you support translations in the future?

### ISSUE THREAD

**Issue by Himmelt** [Bastian/bStats#76]
If you start translation work, I can help with Chinese.

**Comment by DoNotSpamPls** [comment]
Unofficial response incoming: while this is a nice idea, it's most likely a very low priority compared to more often requested features, such as a "Remember Me" option or bar charts, and bStats is a low priority project anyway. So probably don't expect this any time soon.

P.S. Every user who uses custom charts would have to translate them tok, which would be a bit of a hassle.

**Comment by Bastian** [comment]
Thank you for the suggestion and offer to help with translation.
It would be cool to have these kind of translation, but considering the amount of work to translate the website in other languages (and keep them up to date!) I don't think this would be worth the work.
