### ISSUE TITLE
Velocity support

### ISSUE THREAD

**Issue by MicleBrick** [Bastian/bStats#81]
[Velocity](https://velocitypowered.com) is a growing BungeeCord alternative. Request is that similar support for BungeeCord be added for velocity

**Comment by MrIvanPlays** [comment]
https://github.com/Bastian/bStats-Metrics/pull/52 is the continue. It looks like the author of https://github.com/Bastian/bStats-Metrics/pull/39 does not care anymore about it.

**Comment by Andre601** [comment]
Is this still worked on? I would like to have Velocity support...
Even more would it be perhaps an idea to start thinking about creating and providing a platform-independant Metrics class example as plugins like mine may support more than one specific platform, so having a way to f.e. define the platform within the metrics class itself would be a good option to have.

**Comment by Andre601** [comment]
Something I wonder is, why this is still open... Bstats now has Velocity support, even through a native integration by Velocity itself, so this issue should be solved by now, right?
