### ISSUE TITLE
Would you add server-implementation "CatServer"?

### ISSUE THREAD

**Issue by Luohuayu** [Bastian/bStats#82]
It is a Bukkit+Forge server
https://github.com/Luohuayu/CatServer

**Comment by Bastian** [comment]
Can you please give me some more information about this?
Is it something like Paper?

**Comment by Luohuayu** [comment]
It is 1.10.2/1.12.2 Bukkit+Forge server,support both Forge mod and Bukkit plugin,like Kcauldron.

**Comment by MiniDigger** [comment]
Looking at the repo it seems to be a fork that tries to implement bukkit, like cauldron and thermos.
What's also interesting would be the current number of users.
