### ISSUE TITLE
Can't visit pages

### ISSUE THREAD

**Issue by EntityCat** [Bastian/bStats#86]
I use "npm install" to install it,But I can't load the webpages...
Console:

```
> bstats@0.0.0 start /usr/local/src/bStats
> node ./bin/start.js

Master 21278 is running
Worker 21284 started
Worker 21289 started
Worker 21292 started
Worker 21290 started
GET /login - - ms - -
GET /sitemap.xml 304 26.505 ms - -

```

**Comment by Bastian** [comment]
To run bStats locally, you just also
* Setup a redis cluster
* Update the `config.js` file (see https://github.com/Bastian/bStats/blob/master/config.json(
* Run `redisPopulator.js` once (see https://github.com/Bastian/bStats/blob/master/redisPopulator.js)
