### ISSUE TITLE
redisPopulator no responses

### ISSUE THREAD

**Issue by EntityCat** [Bastian/bStats#87]
No any messages

**Comment by Bastian** [comment]
?

**Comment by EntityCat** [comment]
Emmm...
I run the redisPopulator.js already 1 hour,node isn't return or print any message...
Is it normally?

**Comment by Bastian** [comment]
It should usually take less than 1 second, so there's something wrong.
How do you run the class?

**Comment by EntityCat** [comment]
I depoly the redis-clusters by a tool(create-cluster) from redis..
```
./create-cluster start
```
Then I run `node redisPopulator.js`

**Comment by EntityCat** [comment]
Fix:depoly - deploy
