### ISSUE TITLE
Chart as a Picture on a other Website

### ISSUE THREAD

**Issue by Nickdererste** [Bastian/bStats#93]
Hi, I have seen this https://www.spigotmc.org/resources/api-oreocore.64827/ on SpigotMC, how can i make my own banners?

**Comment by McLive** [comment]
https://bstats.org/signatures/<software>/<name>.svg

->
https://bstats.org/signatures/bukkit/SkinsRestorer.svg

![img](https://bstats.org/signatures/bukkit/SkinsRestorer.svg)

**Comment by Nickdererste** [comment]
Thanks
