### ISSUE TITLE
Website doesn't show info.

### ISSUE THREAD

**Issue by Emilius123** [Bastian/bStats#94]
Hello! I thought bStats is a cool service and that I should try that too. I did.
My plugin sent data bu the website doesn't show it. (https://bstats.org/plugin/bukkit/ChatColorz)
That's the log:
`[10:13:58 INFO]: [ChatColorz] Sending data to bStats: {"onlineMode":0,"bukkitVersion":"git-Spigot-dcd1643-e60fc34 (MC: 1.12.2)","serverUUID":"2290cb74-e38a-49a4-b946-23abd9150d29","osVersion":"4.18.0-15-generic","playerAmount":1,"javaVersion":"10.0.2","plugins":[{"pluginVersion":"1.0","pluginName":"ChatColorz","customCharts":[]}],"osArch":"amd64","osName":"Linux","coreCount":4}
[10:13:58 INFO]: [ChatColorz] Sent data to bStats and received response: {"status":"OK"}
`

**Comment by DoNotSpamPls** [comment]
Data is only shown for online servers and since you have shut down your test server, there is no data to display.

**Comment by Bastian** [comment]
![image](https://user-images.githubusercontent.com/5033001/56378652-fa99ef80-620d-11e9-9ca9-464da2636fc3.png)
Past data does exist.
Like @DoNotSpamPls said: When you shutdown your server, the server will no longer be counted on bStats (with a ~30 minute delay).
