### ISSUE TITLE
Lost password

### ISSUE THREAD

**Issue by andrei1058** [Bastian/bStats#95]
I can't find a way to reset my password. Can you please help me?

**Comment by Bastian** [comment]
Please send me a message on Spigot https://www.spigotmc.org/members/btobastian.87698/ or Discord with:
• Your exact bStats username
• Some proof that it is your account (when you message me with the account that published one of the account's plugins on Spigot, that's enough)
• A bcrypt hash of your password (can be generated on this site: https://www.browserling.com/tools/bcrypt (select 12 rounds))

There's no automatic password reset currently.

**Comment by Bastian** [comment]
Done
